/// Equity curves of the latest single-strategy runs (~283k rows), joined to the
/// run metadata in M (no native SQL: Desktop gates native queries behind a
/// per-query approval that breaks unattended refreshes).
table equity_curves

	/// Named 'Strategy Equity' (not 'Equity'): Tabular object names are
	/// case-insensitive per table, so a measure 'Equity' collides with the
	/// `equity` column — the engine rejects it at database creation even though
	/// the TMDL parser accepts it.
	measure 'Strategy Equity' = AVERAGE('equity_curves'[equity])
		formatString: $#,0

	measure 'Buy & Hold Equity' = AVERAGE('equity_curves'[buy_hold_equity])
		formatString: $#,0

	column symbol
		dataType: string
		summarizeBy: none
		sourceColumn: symbol

	column strategy
		dataType: string
		summarizeBy: none
		sourceColumn: strategy

	column ts
		dataType: dateTime
		summarizeBy: none
		sourceColumn: ts

	column equity
		dataType: double
		summarizeBy: average
		sourceColumn: equity

	column buy_hold_equity
		dataType: double
		summarizeBy: average
		sourceColumn: buy_hold_equity

	partition equity_curves = m
		mode: import
		source =
				let
					// Pure M on purpose — no Value.NativeQuery. Power BI gates native
					// database queries behind a per-query user approval
					// (EvaluateNativeQueryUnpermitted on an unattended refresh), so the
					// latest-run-per-(symbol, strategy) selection is done with
					// standard folding-friendly M instead.
					Source = PostgreSQL.Database(PgHost, PgDatabase),
					runs = Source{[Schema="gold",Item="backtest_runs"]}[Data],
					withCurve = Table.SelectRows(runs, each [has_curve] = true),
					slim = Table.SelectColumns(withCurve, {"backtest_run_id", "symbol", "strategy", "executed_at"}),
					latest = Table.Group(
						slim,
						{"symbol", "strategy"},
						{{"latest_run", each Table.First(Table.Sort(_, {{"executed_at", Order.Descending}})), type record}}
					),
					latestIds = Table.SelectColumns(
						Table.ExpandRecordColumn(latest, "latest_run", {"backtest_run_id"}),
						{"symbol", "strategy", "backtest_run_id"}
					),
					curves = Source{[Schema="gold",Item="backtest_equity_curves"]}[Data],
					curvesSlim = Table.SelectColumns(curves, {"backtest_run_id", "ts", "equity", "buy_hold_equity"}),
					joined = Table.NestedJoin(curvesSlim, {"backtest_run_id"}, latestIds, {"backtest_run_id"}, "run", JoinKind.Inner),
					expanded = Table.ExpandTableColumn(joined, "run", {"symbol", "strategy"}),
					typed = Table.TransformColumnTypes(
						Table.SelectColumns(expanded, {"symbol", "strategy", "ts", "equity", "buy_hold_equity"}),
						{{"equity", type number}, {"buy_hold_equity", type number}}
					)
				in
					typed
